server:
  port: 8081

spring:
  application:
    name: oxi-project
  datasource:
    url: jdbc:postgresql://localhost:5432/project
    username: "postgres"
    password: "admin"
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  logging:
    level:
      root: INFO
      com.oxi: DEBUG
jpa:
  hibernate:
    ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
